### ISSUE TITLE
Drive link is not working

### ISSUE THREAD

**Issue by sidd272** [danielschroter/human_value_detector#8]
The drive link for trained models is giving a 404 error can you please provide the updated link

**Comment by danielschroter** [comment]
Hello, 

Than you for your message! You find the relevant model files under the following link now: https://zenodo.org/records/7656534

**Comment by danielschroter** [comment]
I also added the huggingface link to the best-performing single model for easy usage https://huggingface.co/tum-nlp/Deberta_Human_Value_Detector
